trigger: none

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'apisuma'
  containerRegistry: 'bjuztest.azurecr.io'
  acrsecret: aksexamplesuma
  replicaNo: 1
  namespace: 'apisuma'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image
      inputs:
        containerRegistry: 'Container Registry'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/WebApi/Dockerfile'
        tags: '$(tag)'
        
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/WebApi/Apis/apisuma'
        artifact: 'manifests'
        publishLocation: 'pipeline'
      
    

