apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceName }} 
    namespace: {{ .Values.namespace}}
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
    selector:
        app: {{ .Values.serviceName }} 